stages:
  - pull
  - build
  - lint
  - test
  - push
  - deploy
  - cleanup

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

pull:
  stage: pull
  allow_failure: true
  script:
    - docker pull "$CI_REGISTRY_IMAGE":latest

build:
  stage: build
  script:
    - echo "$CI_REGISTRY_IMAGE":latest
    - docker build --tag="$CI_PIPELINE_ID":"$CI_BUILD_REF_NAME" --cache-from="$CI_REGISTRY_IMAGE":latest .

lint:
  stage: lint
  script:
    - export CI_PIPELINE_ID=$CI_PIPELINE_ID
    - export CI_BUILD_REF_NAME=$CI_BUILD_REF_NAME
    - docker-compose -p "$CI_PIPELINE_ID" -f docker-compose.test.yml run app flake8 .

test:
  stage: test
  script:
    - export CI_PIPELINE_ID=$CI_PIPELINE_ID
    - export CI_BUILD_REF_NAME=$CI_BUILD_REF_NAME
    - docker-compose -p "$CI_PIPELINE_ID" -f docker-compose.test.yml run app sh /scripts/test.sh
  artifacts:
    paths:
      - coverage/

pages:
 stage: deploy
 dependencies:
   - test
 script:
   - mv htmlcov public
 artifacts:
   paths:
     - public

push image:
  stage: push
  only:
    - tags
    - master
  script:
    - docker tag "$CI_PIPELINE_ID":"$CI_BUILD_REF_NAME" "$CI_REGISTRY_IMAGE":"$CI_BUILD_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE":"$CI_BUILD_REF_NAME"

push latest:
  stage: push
  script:
    - docker tag "$CI_PIPELINE_ID":"$CI_BUILD_REF_NAME" "$CI_REGISTRY_IMAGE":latest
    - docker push "$CI_REGISTRY_IMAGE":latest

deploy to prod:
  stage: deploy
  when: manual
  only:
    - master
    - tags
  script:
    - docker-compose -f docker-compose.deploy.yml pull
    - docker-compose -f docker-compose.deploy.yml down
    - docker-compose -f docker-compose.deploy.yml up -d

cleanup:
  stage: cleanup
  when: always
  script:
    - export CI_PIPELINE_ID=$CI_PIPELINE_ID
    - export CI_BUILD_REF_NAME=$CI_BUILD_REF_NAME
    - docker rmi -f "$CI_PIPELINE_ID":"$CI_BUILD_REF_NAME"
    - docker-compose -f docker-compose.test.yml down --remove-orphans
    - docker-compose -f docker-compose.ci.yml down --remove-orphans
